= Ansible and Puppet workshop

Basically, I want to show case a simple comparison between the two tools for installing an existing rpm and configuring it. My intuition is that they will function very similarily and with similar difficulties setting up.

== Use Case

''''
I have a custom rpm that I want installed, but the rpm needs individual configurations per project that is installing it. Generally if it was the same across the board we would simple write an rpm and be done with, however it is not that easy if there are configuration variations between consumers. We are going to simulate this variation by doing the configurations with configuration management tool.

''''

.What we're going to do
. Build a custom RPM for EAP installation
. Configure Java Vault a configuration file for EAP
. Use configuration management tool to install and configure EAP

== The  RPM
On the host machine download this project and then build the rpm and create the repository. We will then use this to push to the remote server for installation.

. Download project

. https://www.jboss.org/download-manager/file/jboss-eap-6.4.0.GA.zip[Download EAP]

. Add product to installs directory

. Create link to installs directory

[source,bash]
----
$ cd /<project-home>/ansible-puppet-workship
$ ln installs/jboss-eap-6.4.0.zip support/rpmbuild/SOURCES
----

. Build RPM

[source, bash]
----
$ rpmbuild --define "_topdir ${PWD}/support/rpmbuild" -ba -v ./support/rpmbuild/SPECS/jboss-eap-6.4.spec
----

.Create yum repository

== Ansible



== Puppet

