---
- hosts: minion01.rhel7.labs

  remote_user: redhatter
  sudo: yes

  tasks:
  - name: Copy JBoss EAP RPM 
    copy: src=/mnt/ansible-puppet-workshop/support/rpmbuild/RPMS/x86_64/jboss-eap-6.4-1.0-1.el7.x86_64.rpm dest=/opt/myrepo/

  - name: Copy jboss repo config file  
    copy: src=/mnt/ansible-puppet-workshop/support/data/jboss-repo.repo dest=/opt/myrepo/

  - name: Ensure createrepo is installed
    yum: name=createrepo state=present

  - name: Ensure yum-config-manager is installed
    yum: name=yum-utils state=present

  - name: Create repository for yum
    command: /usr/bin/createrepo --database /opt/myrepo 

  - name: Add JBoss EAP repository to yum
    command: /usr/bin/yum-config-manager --add-repo /opt/myrepo/jboss-repo.repo --enable 

  - name: Install JBoss EAP
    yum: name=jboss-eap-6.4 state=present
    notify:
    - start eap
#  - name: Deploy Hello World application
#    copy: 
#      src=/mnt/ansible-puppet-workshop/support/bin/helloworld-ansible/target/jboss-helloworld-ansible.war 
#      dest=/opt/jboss/jboss-eap-6.4/standalone/deployments
#    - start eap

  handlers:
  - name: start eap
    service: name=jboss-as-standalone state=started

